---
title: "Tarea Introducción R"
subtitle: "T6_IntroR"
author: "Francisco Javier Mendoza Proaño"
date: '2022-02-26'
output:
  html_document:
    mathjax: "http://example.com/MathJax.js"
    self_contained: true
    fig_height: 6
    fig_width: 8
    theme: journal
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TAREA 1: TIPOS DE DATOS

Se soluciona la TAREA 1: TIPOS DE DATOS, basado en los archivos proporcionados en clase.

### Ejericicio 1
Crear un identificador de nombre "ciudad" y asigne como valor el nombre de alguna ciudad.

```{r ciudad}
#Se asigna un valor al idetificador de ciudad
#En este caso se lo asigna con el nombre Tena
ciudad<-"Tena"
#Se imprime el valor del identificador
ciudad
```

### Ejercicio 2
Crear un identificador de nombre "pais_andes" y asigne como valor los nombres de los países por donde cruza la cordillera de Los Andes.

```{r pais_andes}
#Se asigna un valor al idetificador de pais_andes
#En este caso se lo asigna los nombres de los países por los que pasa la Coordillera de los Andes
#Se toma en cuenta Venezuela porque pasa parte de la Cooridellera de los Andes
#Al ser cadenas de caracteres se debe emepzar la variable como tipo .character
pais_andes<-as.character(c("Argentina", "Bolivia", "Chile", "Colombia", "Ecuador", "Perú", "Venezuela"))
#Se imprimen los datos
str(pais_andes)
print(pais_andes)
```